tproxy-port: 7890
redir-port: 7891
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
# BAGIAN ATAS, JANGAN DI EDIT > INFO CEK GRUP GATCHA
proxy-groups:
 - name: akun
   type: select 
   use: 
   - akun

proxy-providers:
  akun:
    type: file
    path: "/data/adb/clash/akun.yaml" 
    health-check: 
      enable: false 
      url: http://www.gstatic.com/generate_204 
      interval: 300
rules:
  - MATCH,akun
